vAirline/Controllers/BookingsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using vAirline.Models;

namespace vAirline.Controllers
{
    [Authorize]
    public class BookingsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Bookings
        public ActionResult Index()
        {
            ViewBag.PassengerUserName = User.Identity.GetUserName();

            var bookings = db.Bookings.Include(b => b.Flight).Include(b => b.Passenger).Include(b => b.Seat);
            return View(bookings.ToList());
        }

        // GET: Bookings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // GET: Bookings/Create
        public ActionResult Create(int id)
        {
            BookingViewModel model = new BookingViewModel();
            model.Flight = db.Flights.Find(id);
            TempData["FlightID"] = model.Flight.FlightID;

            return View(model);
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BookingViewModel model)
        {
            Flight flight = db.Flights.Find(TempData["FlightID"]);

            try
            {
                // Add passenger
                if (ModelState.IsValid)
                {
                    Passenger passenger;
                    Passenger currPassenger;
                    string username = User.Identity.GetUserName();

                    try
                    {
                        currPassenger = db.Passengers.Where(p => p.PassengerUserName == username).Single();
                        passenger = currPassenger;
                    }
                    catch (System.InvalidOperationException)
                    {
                        passenger = new Passenger
                        {
                            PassengerFullName = model.FullName,
                            PassengerUserName = User.Identity.GetUserName(),
                            PassengerPassportNo = model.PassportNo,
                            PassengerAge = model.Age,
                            PassengerGender = model.Gender
                        };

                        db.Passengers.Add(passenger);
                        db.SaveChanges();
                    }

                    // Add seat
                    int bookingSeat;
                    Seat seatToUpdate;

                    foreach (string seat in model.BookingSeats)
                    {
                        if (!(string.IsNullOrEmpty(seat)))
                        {
                            bookingSeat = int.Parse(seat);

                            seatToUpdate = db.Seats.Where(s => s.SeatNumber == bookingSeat && s.FlightID == flight.FlightID).Single();

                            if (TryUpdateModel(seatToUpdate, "", new string[] { "SeatID", "SeatNumber", "FlightClass", "SeatAvailable", "FlightID", "PassengerID", "BookingPrice" }))
                            {
                                try
                                {
                                    seatToUpdate.SeatAvailable = false;
                                    seatToUpdate.PassengerID = passenger.PassengerID;

                                    if (ModelState.IsValid)
                                    {
                                        db.Entry(seatToUpdate).State = EntityState.Modified;
                                        db.SaveChanges();

                                        // Update seat count
                                        int seatCount;

                                        if (seatToUpdate.SeatLocation.Equals("Left"))
                                        {
                                            seatCount = flight.LeftSeat;
                                            flight.LeftSeat = --seatCount;
                                        }
                                        else if (seatToUpdate.SeatLocation.Equals("Middle"))
                                        {
                                            seatCount = flight.MiddleSeat;
                                            flight.MiddleSeat = --seatCount;
                                        }
                                        else
                                        {
                                            seatCount = flight.RightSeat;
                                            flight.RightSeat = --seatCount;
                                        }

                                        seatCount = flight.TotalSeatsAvailable;
                                        flight.TotalSeatsAvailable = --seatCount;

                                        db.Entry(flight).State = EntityState.Modified;
                                        db.SaveChanges();

                                        // Add booking
                                        Booking booking = new Booking
                                        {
                                            BookingDateTime = DateTime.Now,
                                            BookingPrice = flight.PricePerSeat,
                                            PassengerID = passenger.PassengerID,
                                            FlightID = flight.FlightID,
                                            SeatID = seatToUpdate.SeatID
                                        };

                                        db.Bookings.Add(booking);
                                        db.SaveChanges();
                                    }
                                }
                                catch (DataException)
                                {
                                    ModelState.AddModelError("", "Unable to save changes.");
                                }
                            }
                        }
                    }

                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                return View(model);
            }

            // Return to previous page if fail
            return View(model);
        }

        // GET: Bookings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            ViewBag.FlightID = new SelectList(db.Flights, "FlightID", "FlightCode", booking.FlightID);
            ViewBag.PassengerID = new SelectList(db.Passengers, "PassengerID", "PassengerFullName", booking.PassengerID);
            ViewBag.SeatID = new SelectList(db.Seats, "SeatID", "SeatLocation", booking.SeatID);
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BookingID,BookingDateTime,PassengerID,FlightID,SeatID,BookingPrice")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                db.Entry(booking).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FlightID = new SelectList(db.Flights, "FlightID", "FlightCode", booking.FlightID);
            ViewBag.PassengerID = new SelectList(db.Passengers, "PassengerID", "PassengerFullName", booking.PassengerID);
            ViewBag.SeatID = new SelectList(db.Seats, "SeatID", "SeatLocation", booking.SeatID);
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Booking booking = db.Bookings.Find(id);

            // Change seat status to available
            Seat seat = db.Seats.Find(booking.SeatID);
            seat.SeatAvailable = true;
            seat.PassengerID = null;
            db.Entry(seat).State = EntityState.Modified;
            db.SaveChanges();

            // Remove booking
            db.Bookings.Remove(booking);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

vAirline/Controllers/FlightsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using vAirline.Models;

namespace vAirline.Controllers
{
    public class FlightsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Flights
        public ActionResult Index()
        {

            var flights = db.Flights.Include(f => f.Plane);
            return View(flights.ToList());
        }

        // GET: Flights/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flight flight = db.Flights.Find(id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            return View(flight);
        }

        // GET: Flights/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            FlightViewModel model = new FlightViewModel();
            ViewBag.Planes = db.Planes.ToArray();

            return View(model);
        }

        // POST: Flights/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FlightViewModel model)
        {
            if (ModelState.IsValid)
            {
                // Find chosen departure and arrival airports
                Airport departureAirport = db.Airports.Find(int.Parse(model.DepartureAirportID));
                Airport arrivalAirport = db.Airports.Find(int.Parse(model.ArrivalAirportID));

                // Add new flight to database
                Flight flight = new Flight
                {

                    DepartureAirportCode = departureAirport.AirportCode,
                    DepartureDateTime = model.DepartureDateTime,
                    ArrivalAirportCode = arrivalAirport.AirportCode,
                    ArrivalDateTime = model.ArrivalDateTime,
                    PricePerSeat = model.PricePerSeat,
                    LeftSeat = model.LeftSeat,
                    MiddleSeat = model.MidSeat,
                    RightSeat = model.RightSeat,
                    TotalSeatsAvailable = model.TotalSeatsAvailable,
                    PlaneID = model.PlaneID
                };

                db.Flights.Add(flight);
                db.SaveChanges();

                // Generate flight code based on countries
                string flightID = flight.FlightID.ToString();
                string departureCountry = departureAirport.AirportCountry[0].ToString();
                string arrivalCountry = arrivalAirport.AirportCountry[0].ToString();

                flight.FlightCode = departureCountry + arrivalCountry + flightID;

                db.Entry(flight).State = EntityState.Modified;
                db.SaveChanges();

                // Generate seats for new flight
                int leftSeatCount = flight.LeftSeat;
                int leftMidSeatCount = leftSeatCount + flight.MiddleSeat;
                int totalSeatCount = flight.TotalSeatsAvailable;

                Seat seat;

                for (int i = 1; i <= totalSeatCount; i++)
                {
                    seat = new Seat
                    {
                        SeatNumber = i,
                        SeatLocation = "Left",
                        FlightID = flight.FlightID
                    };

                    if (i > leftSeatCount && i <= leftMidSeatCount)
                    {
                        seat.SeatLocation = "Middle";
                    }
                    else if (i > leftMidSeatCount)
                    {
                        seat.SeatLocation = "Right";
                    }

                    db.Seats.Add(seat);
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }

            ViewBag.Planes = db.Planes.ToArray();
            return View(model);
        }

        [Authorize(Roles = "admin")]
        // GET: Flights/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flight flight = db.Flights.Find(id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            ViewBag.PlaneID = new SelectList(db.Planes, "PlaneID", "PlaneModel", flight.PlaneID);
            return View(flight);
        }

        // POST: Flights/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FlightID,FlightCode,DepartureAirportCode,DepartureDateTime,ArrivalAirportCode,ArrivalDateTime,PricePerSeat,LeftSeat,MiddleSeat,RightSeat,TotalSeatsAvailable,PlaneID")] Flight flight)
        {
            if (ModelState.IsValid)
            {
                db.Entry(flight).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PlaneID = new SelectList(db.Planes, "PlaneID", "PlaneModel", flight.PlaneID);
            return View(flight);
        }

        // GET: Flights/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flight flight = db.Flights.Find(id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            return View(flight);
        }

        // POST: Flights/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Flight flight = db.Flights.Find(id);
            db.Flights.Remove(flight);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

vAirline/Views/Flights/Create.cshtml
@model vAirline.Models.FlightViewModel

@{
    ViewBag.Title = "Create";
}



<script type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js"></script>
<div class="container getDown">
    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "addFlightForm" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Create Flight</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.DepartureAirportID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.DropDownListFor(model => model.DepartureAirportID, Model.Airports, htmlAttributes: new { @class = "form-control", @id = "departureAirport" })
                    @Html.ValidationMessageFor(model => model.DepartureAirportID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.DepartureDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.DepartureDateTime, new { htmlAttributes = new { @class = "form-control datetimepicker", @id = "departureDateTimePicker" } })
                    @Html.ValidationMessageFor(model => model.DepartureDateTime, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ArrivalAirportID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.DropDownListFor(model => model.ArrivalAirportID, Model.Airports, htmlAttributes: new { @class = "form-control", @id = "arrivalAirport" })
                    @Html.ValidationMessageFor(model => model.ArrivalAirportID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ArrivalDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.ArrivalDateTime, new { htmlAttributes = new { @class = "form-control datetimepicker", @id = "arrivalDateTimePicker" } })
                    @Html.ValidationMessageFor(model => model.ArrivalDateTime, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PricePerSeat, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.PricePerSeat, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PricePerSeat, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.LeftSeat, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.LeftSeat, new { htmlAttributes = new { @class = "form-control", @id = "leftSeat", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.LeftSeat, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.MidSeat, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.MidSeat, new { htmlAttributes = new { @class = "form-control", @id = "midSeat", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.MidSeat, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.RightSeat, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.RightSeat, new { htmlAttributes = new { @class = "form-control", @id = "rightSeat", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.RightSeat, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.TotalSeatsAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.TotalSeatsAvailable, new { htmlAttributes = new { @class = "form-control", @id = "totalSeat", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.TotalSeatsAvailable, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PlaneID, "PlaneID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-8">
                    @Html.DropDownListFor(model => model.PlaneID, Model.Planes, htmlAttributes: new { @class = "form-control", @id = "planeModels" })
                    @Html.ValidationMessageFor(model => model.PlaneID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="button" value="Create" class="btn btn-primary" id="submitForm" />
                </div>
            </div>
        </div>
    }
    <div>
        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-warning" })
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquerypicker")
}

<script type="text/javascript">
    var leftSeat;
    var midSeat;
    var rightSeat;
    var totalSeat;
    var planes;

    $(document).ready(function () {

        planes = @Html.Raw(
            Json.Encode(
                ((IEnumerable<vAirline.Models.Plane>)ViewBag.Planes).Select(plane => new
                    {
                        planeModel = plane.PlaneModel,
                        leftSeat = plane.LeftSeat,
                        midSeat = plane.MiddleSeat,
                        rightSeat = plane.RightSeat
                    })
            )
        );

        updateSeat(0);

        $('.datetimepicker').datetimepicker();
        
        $('#planeModels').change(function()
        {
            var count = this.value - 1;

            updateSeat(count);
        });

        $('#submitForm').click(function()
        {
            if ($('#departureAirport').val() == $('#arrivalAirport').val())
            {
                alert("Departure and destination must not be the same.");
            }
           else
            {
                $('#addFlightForm').submit();
            }
        });
    });

    function updateSeat(count) {

        leftSeat = planes[count].leftSeat;
        midSeat = planes[count].midSeat;
        rightSeat = planes[count].rightSeat;
        totalSeat = leftSeat + midSeat + rightSeat;

        $('#leftSeat').val(leftSeat);
        $('#midSeat').val(midSeat);
        $('#rightSeat').val(rightSeat);
        $('#totalSeat').val(totalSeat);
    }
</script>

vAirline/Views/Flights/Delete.cshtml
@model vAirline.Models.Flight

@{
    ViewBag.Title = "Delete";
}


<div class="container getDown">
    <h3>Are you sure you want to delete this flight?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Plane.PlaneModel)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Plane.PlaneModel)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.DepartureAirportCode)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.DepartureAirportCode)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.DepartureDateTime)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.DepartureDateTime)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ArrivalAirportCode)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ArrivalAirportCode)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ArrivalDateTime)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ArrivalDateTime)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.PricePerSeat)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.PricePerSeat)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.LeftSeat)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.LeftSeat)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.MiddleSeat)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.MiddleSeat)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.RightSeat)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.RightSeat)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.TotalSeatsAvailable)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.TotalSeatsAvailable)
            </dd>
        </dl>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-danger" /> |
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-warning" })
            </div>
        }
    </div>
</div>

vAirline/Views/Flights/Details.cshtml
@model vAirline.Models.Flight

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div class="container getDown">
    <h4>Flight Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Plane.PlaneModel)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Plane.PlaneModel)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DepartureAirportCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DepartureAirportCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DepartureDateTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DepartureDateTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ArrivalAirportCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ArrivalAirportCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ArrivalDateTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ArrivalDateTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PricePerSeat)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PricePerSeat)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LeftSeat)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LeftSeat)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MiddleSeat)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MiddleSeat)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RightSeat)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RightSeat)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TotalSeatsAvailable)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TotalSeatsAvailable)
        </dd>
    </dl>
    @if (User.IsInRole("admin"))
    {
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.FlightID }, new { @class = "btn btn-default" }) |
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-warning" })
        </p>
    }
    else
    {
        <p>
            @Html.ActionLink("Book", "Create", "Bookings", new { id = Model.FlightID }, new { @class = "btn btn-primary" }) |
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-warning" })
        </p>
    }
</div>